#include <stdio.h>
#include <stdlib.h>
#include <cuda_runtime.h>

const char p_name[19] = "deviceProperties: ";

void printDeviceProperties(struct cudaDeviceProp *devProp)
{
	if (devProp == NULL){
		printf("%s: error with printDeviceProperties: devProp is NULL pointer.\n", p_name);
		exit(1);
	}
	// Yes the print has been generated by Gemini okay? It was BOOORIIING
	printf("--------------------------------------------------------------------------------\n");
	printf("| Property                      | Value                                        |\n");
	printf("--------------------------------------------------------------------------------\n");
	printf("| Name                          | %-40s |\n", devProp->name);
	printf("| Total Global Mem (Bytes)      | %-40zu |\n", devProp->totalGlobalMem);
	printf("| Shared Mem Per Block (Bytes)  | %-40zu |\n", devProp->sharedMemPerBlock);
	printf("| Registers Per Block           | %-40d |\n", devProp->regsPerBlock);
	printf("| Warp Size                     | %-40d |\n", devProp->warpSize);
	printf("| Mem Pitch (Bytes)             | %-40zu |\n", devProp->memPitch);
	printf("| Max Threads Per Block         | %-40d |\n", devProp->maxThreadsPerBlock);
	printf("| Max Threads Dim [X, Y, Z]     | [%-4d, %-4d, %-4d]                             |\n",
		   devProp->maxThreadsDim[0], devProp->maxThreadsDim[1], devProp->maxThreadsDim[2]);
	printf("| Max Grid Size [X, Y, Z]       | [%-4d, %-4d, %-4d]                             |\n",
		   devProp->maxGridSize[0], devProp->maxGridSize[1], devProp->maxGridSize[2]);
	printf("| Clock Rate (kHz)              | %-40d |\n", devProp->clockRate);
	printf("| Total Const Mem (Bytes)       | %-40zu |\n", devProp->totalConstMem);
	printf("| Major                         | %-40d |\n", devProp->major);
	printf("| Minor                         | %-40d |\n", devProp->minor);
	printf("| Texture Alignment (Bytes)     | %-40zu |\n", devProp->textureAlignment);
	printf("| Device Overlap                | %-40d |\n", devProp->deviceOverlap);
	printf("| Multi Processor Count         | %-40d |\n", devProp->multiProcessorCount);
	printf("| Kernel Exec Timeout Enabled   | %-40d |\n", devProp->kernelExecTimeoutEnabled);
	printf("| Integrated                    | %-40d |\n", devProp->integrated);
	printf("| Can Map Host Memory           | %-40d |\n", devProp->canMapHostMemory);
	printf("| Compute Mode                  | %-40d |\n", devProp->computeMode);
	printf("| Max Texture 1D                | %-40d |\n", devProp->maxTexture1D);
	printf("| Max Texture 2D [Width, Height]| [%-4d, %-4d]                             |\n",
		   devProp->maxTexture2D[0], devProp->maxTexture2D[1]);
	printf("| Max Texture 3D [W, H, D]      | [%-4d, %-4d, %-4d]                             |\n",
		   devProp->maxTexture3D[0], devProp->maxTexture3D[1], devProp->maxTexture3D[2]);
	printf("| Max Texture 1D Layered [W, Layers] | [%-4d, %-4d]                             |\n",
		   devProp->maxTexture1DLayered[0], devProp->maxTexture1DLayered[1]);
	printf("| Max Texture 2D Layered [W, H, Layers]| [%-4d, %-4d, %-4d]                             |\n",
		   devProp->maxTexture2DLayered[0], devProp->maxTexture2DLayered[1], devProp->maxTexture2DLayered[2]);
	printf("| Surface Alignment (Bytes)     | %-40zu |\n", devProp->surfaceAlignment);
	printf("| Concurrent Kernels            | %-40d |\n", devProp->concurrentKernels);
	printf("| ECC Enabled                   | %-40d |\n", devProp->ECCEnabled);
	printf("| PCI Bus ID                    | %-40d |\n", devProp->pciBusID);
	printf("| PCI Device ID                 | %-40d |\n", devProp->pciDeviceID);
	printf("| PCI Domain ID                 | %-40d |\n", devProp->pciDomainID);
	printf("| TCC Driver                    | %-40d |\n", devProp->tccDriver);
	printf("| Async Engine Count            | %-40d |\n", devProp->asyncEngineCount);
	printf("| Unified Addressing            | %-40d |\n", devProp->unifiedAddressing);
	printf("| Memory Clock Rate (kHz)       | %-40d |\n", devProp->memoryClockRate);
	printf("| Memory Bus Width (bits)       | %-40d |\n", devProp->memoryBusWidth);
	printf("| L2 Cache Size (Bytes)         | %-40d |\n", devProp->l2CacheSize);
	printf("| Max Threads Per MultiProc     | %-40d |\n", devProp->maxThreadsPerMultiProcessor);
	printf("--------------------------------------------------------------------------------\n");
}

int main()
{
	printf("%s: \n", p_name);

	int deviceCount;
	cudaError_t error_id = cudaGetDeviceCount(&deviceCount);
	if (error_id != cudaSuccess)
	{
		printf("%s: Error with cudaGetDeviceCount().\n", p_name);
		exit(1);
	}

	printf("%s: Found %d devices.\n", p_name, deviceCount);

	struct cudaDeviceProp devProp;

	for (unsigned int i = 0; i < deviceCount; i++)
	{
		error_id = cudaGetDeviceProperties(&devProp, i);

		if (error_id != cudaSuccess)
		{
			printf("%s: Error with cudaGetDeviceProperties() for device %d.\n", p_name, i);
			exit(1);
		}
		printDeviceProperties(&devProp);
	}

	return 0;
}